---
name: 'Prep for book tests'
description: 'install dependencies for tdd book tests'
inputs:
  test_chapter:  # id of input
    required: true
runs:
  using: "composite"

  # env:
  #   MOZ_HEADLESS: 1
  #   LC_ALL: en_GB.UTF-8
  #   LANG: en_GB.UTF8
  #   LANGUAGE: "en_GB:en"

  steps:
    - uses: actions/checkout@v4

    - name: checkout submodules
      shell: bash
      run: |
        sed -i 's_git@github.com:_https://github.com/_' .gitmodules
        git submodule update --init --recursive

    - name: setup Git
      shell: bash
      run: |
        git config --global user.email "elspeth@example.com"
        git config --global user.name "Elspeth See-Eye"
        git config --global init.defaultBranch main

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install apt stuff and other dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa
        sudo apt update -y
        sudo apt install -y \
          asciidoctor \
          language-pack-en \
          ruby-coderay \
          ruby-pygments.rb \
          firefox-esr \
          tree \
          locales
        sudo locale-gen en_GB.UTF-8

    - name: Install Python requirements.txt
      shell: bash
      run: |
        pip install .

    - name: Check environment
      shell: bash
      run: |
        locale -a
        locale
        env

    - name: Run chapter test
      shell: bash
      run: |
        make  ${{ inputs.test_chapter }}

    - name: Archite the built html files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: built-html
        path: |
          *.html
