---
name: 'Prep for book tests'
description: 'install dependencies for tdd book tests'
inputs:
  test_chapter:  # id of input
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"

  # env:
  #   MOZ_HEADLESS: 1
  #   LC_ALL: en_GB.UTF-8
  #   LANG: en_GB.UTF8
  #   LANGUAGE: "en_GB:en"

  steps:
    - uses: actions/checkout@v3

    - name: checkout submodules
      shell: bash
      run: |
        sed -i 's_git@github.com:_https://github.com/_' .gitmodules
        git submodule update --init --recursive

    - name: setup Git
      shell: bash
      run: |
        git config --global user.email "elspeth@example.com"
        git config --global user.name "Elspeth See-Eye"
        git config --global init.defaultBranch main

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install apt stuff and other dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa
        sudo apt update -y
        sudo apt install -y \
          asciidoctor \
          language-pack-en \
          ruby-coderay \
          firefox-esr \
          tree \
          locales
        sudo locale-gen en_GB.UTF-8

    # - name: Install asciidoc and other ruby dependencies
    #   run: |
    #     sudo gem install coderay

    - name: Install Python requirements.txt
      shell: bash
      run: |
        pip install .

    - name: Check environment
      shell: bash
      run: |
        locale -a
        locale
        env

    - name: Run chapter test
      shell: bash
      run: |
        make  ${{ inputs.test_chapter }}
